proserver:
  build: .
  container_name: proserver
  ports:
    - "4282:4282"
    - "4283:4283"
    - "4285:4285"
    - "4286:4286"
  volumes_from:
    - data
data:
  # image: tianon/true:latest
  image: busybox:latest
  container_name: proserver_data
  volumes:
    # Log files
    - /var/log/proserver
    # Default backup destination
    - /var/opt/proserver
    # System settings and binarys
    - /opt/proserver
    # Using synology local disk space outside container.
    #- /volume1/code42/:/opt/code42
  command: /bin/echo
